export const TradePair = {
  BTCUSDT: {
    trade_pair_id: "BTCUSDT",
    trade_pair: "BTC/USDT",
    fees: 0.001,
    min_leverage: 0.1,
    max_leverage: 5,
    trade_pair_category: "crypto",
  },
  ETHUSDT: {
    trade_pair_id: "ETHUSDT",
    trade_pair: "ETH/USDT",
    fees: 0.001,
    min_leverage: 0.1,
    max_leverage: 5,
    trade_pair_category: "crypto",
  },
  XRPUSDT: {
    trade_pair_id: "XRPUSDT",
    trade_pair: "XRP/USDT",
    fees: 0.001,
    min_leverage: 0.1,
    max_leverage: 5,
    trade_pair_category: "crypto",
  },
  DOGEUSDT: {
    trade_pair_id: "DOGEUSDT",
    trade_pair: "DOGE/USDT",
    fees: 0.001,
    min_leverage: 0.1,
    max_leverage: 5,
    trade_pair_category: "crypto",
  },
  SOLUSDT: {
    trade_pair_id: "SOLUSDT",
    trade_pair: "SOL/USDT",
    fees: 0.001,
    min_leverage: 0.1,
    max_leverage: 5,
    trade_pair_category: "crypto",
  },
};
